### ISSUE TITLE
Broken by changes on Go tip/master

### ISSUE THREAD

**Issue by slimsag** [elazarl/go-bindata-assetfs#12]
Any code described in the ["Without running binary tool" section shows](https://github.com/elazarl/go-bindata-assetfs#without-running-binary-tool) is broken by some changes on Go tip/master. The following program can reproduce the issue:

```
package main

import "github.com/elazarl/go-bindata-assetfs"

func main() {
        _ = http.FileServer(&assetfs.AssetFS{})
}
```

which produces:

```
# github.com/elazarl/go-bindata-assetfs
../assetfs.go:77: AssetFile.Size is ambiguous
../assetfs.go:77: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
	*AssetFile does not implement os.FileInfo (missing Size method)
../assetfs.go:116: AssetDirectory.Size is ambiguous
../assetfs.go:116: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
	*AssetDirectory does not implement os.FileInfo (missing Size method)
```

This is because `AssetFile` is defined as:

```
type AssetFile struct {
	*bytes.Reader
	io.Closer
	FakeFile
}
```

A Go commit in tip (https://github.com/golang/go/commit/c264c87335ff4b3111d43f830dbe37eac1509f2e) added a `Size` method to `*bytes.Reader`, and since `FakeFile` also has a `Size` method -- it's ambiguous and thus breaks.

**Comment by shurcooL** [comment]
I think this can be fixed by simply removing `(f *FakeFile) Size() int64` method for Go 1.5 (via a build constraint), right?

Although perhaps it would be easier to avoid using struct embedding, and instead do:

```Go
type AssetFile struct {
	r *bytes.Reader
	io.Closer
	FakeFile
}

func (af *AssetFile) Read(b []byte) (n int, err error) {
	return af.r.Read(b)
}
```

**Comment by shurcooL** [comment]
Or, even better:

```Go
type AssetFile struct {
	io.Reader
	io.Closer
	FakeFile
}
```

**Comment by elazarl** [comment]
I think avoiding struct embedding is the best solution.

Do you want to submit a pull request?

(Many thanks for reporting this).

**Comment by shurcooL** [comment]
> Do you want to submit a pull request?

If you mean me, I do not have enough bandwidth for that, sorry.

**Comment by slimsag** [comment]
@elazarl @shurcooL I can send one next weekend sometime :smile:

**Comment by elazarl** [comment]
Stephen, thanks, I'll appreciate it.

On Sun, Apr 12, 2015 at 9:39 AM, Stephen Gutekanst <notifications@github.com

**Comment by petermattis** [comment]
@slimsag this was fixed by #13. Just stumbled across this issue now after getting a different fix merged.

**Comment by slimsag** [comment]
@petermattis thank you! :) I can confirm that fixed the issue [with our code as well](https://github.com/sourcegraph/appdash/pull/61).

**Comment by elazarl** [comment]
@slimsag Wow! Sourcegraph is using my code. I'm very flattered, I guess I'll have to be more careful not to break anything with future commits ;-)
