### ISSUE TITLE
Cannot read bindata.go open bindata.go: no such file or directory

### ISSUE THREAD

**Issue by themihai** [elazarl/go-bindata-assetfs#16]
I fail to see how this would work because it seems the constant `bindatafile` [0] is never created so the call is doomed to fail isn't it ? Is this supposed to be created in a different taks? 

``go-bindata-assetfs -o bin.go dist/...

Cannot read bindata.go open bindata.go: no such file or directory``

[0] https://github.com/elazarl/go-bindata-assetfs/blob/master/go-bindata-assetfs/main.go#L44

**Comment by elazarl** [comment]
Thanks for the PR!

Is there a reason not to do that like the isDebug function does that?

**Comment by mephux** [comment]
@elazarl I still get this output on each run - am I missing something.

**Comment by kamilchm** [comment]
Me too. Can't use ``-o`` without this message :(

**Comment by DenBeke** [comment]
+1
