### ISSUE TITLE
Question: Does this work well with CDN too?

### ISSUE THREAD

**Issue by cayter** [elazarl/go-bindata-assetfs#21]
Has anyone tested it with CDN yet?

**Comment by elazarl** [comment]
Not sure how CDN relate to the project.

Can you give an example?

**Comment by cayter** [comment]
Say we use this package to host the assets that reside in memory, will CDN servers fetch the assets and cache them without any problems?

**Comment by elazarl** [comment]
Depends of what you put in the headers.

**Comment by cayter** [comment]
Can help to elaborate a bit more? The assets I'm talking about here are just JS, CSS, HTML and images. I think they would be fine right?

**Comment by elazarl** [comment]
CDNs requires to add HTTP headers which states for how long would they
cache it.

This is not directly related to this package.

**Comment by cayter** [comment]
Oh yeah. You're talking about the`max-age` header right? But yeah, if I'm not mistaken, CDN servers should be able to read and cache the assets normally just like any other web servers serving static assets.

**Comment by markwallsgrove** [comment]
@cayter you just need to send some headers to make sure the CDN caches the file correctly. Something like the following should do the trick.

```
func cacheHeader(ttl string, handler http.Handler) http.Handle {
    return http.Handle(func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Cache-Control", "max-age:" + ttl + ", public")
        handler.ServeHTTP(w, r)
    })
}

http.HandleFunc("/", cacheHeader("290304000", http.FileServer(AssetFS()))
```

**Comment by markwallsgrove** [comment]
@cayter does this answer your question?

**Comment by cayter** [comment]
yeah thanks.
