### ISSUE TITLE
Flag provided but not defined: -prefix

### ISSUE THREAD

**Issue by FrancoisBs** [elazarl/go-bindata-assetfs#22]
The merge of #16 broke my build.

Error message : 
```
flag provided but not defined: -prefix
```
From now we can't use ```go-bindata``` arguments ?

**Comment by shurcooL** [comment]
It's because `flag.Parse()` is called directly. Instead, a new flag set should be created, like for the debug flag.

**Comment by elazarl** [comment]
I reverted the commit. I didn't remember correctly that it was untested. I'll try to find time and fix the issue during the weekend.

Thanks, and sorry.

**Comment by FrancoisBs** [comment]
Closed by d5cac425555ca5cf00694df246e04f05e6a55150
Thanks,
