### ISSUE TITLE
AssetInfo - runtime error: invalid memory address 

### ISSUE THREAD

**Issue by mephux** [elazarl/go-bindata-assetfs#30]
I get a runtime error when using AssetInfo(name) on line (https://github.com/elazarl/go-bindata-assetfs/blob/master/assetfs.go#L148). I can't seem to figure out why though. The file is there.. any ideas?

**Comment by mephux** [comment]
ops, fixed it - sorry.

**Comment by artushin** [comment]
What was the issue? I just ran into the same problem. Worked in my dev environment but doesn't work in my docker container.

**Comment by artushin** [comment]
Got it. For anyone else getting this issue, the probable was not including AssetInfo in the config: "&assetfs.AssetFS{Asset: Asset, AssetDir: AssetDir, AssetInfo: AssetInfo, Prefix: "dist"}," after go get -u pulled in the merge of AssetInfo support.
