### ISSUE TITLE
os package imported twice

### ISSUE THREAD

**Issue by imakewebthings** [elazarl/go-bindata-assetfs#41]
[A line from a PR that was merged yesterday](https://github.com/elazarl/go-bindata-assetfs/pull/40/files#diff-bd286d4fea61eaa5cb1ce5ceaa65b503R70) is causing generated files to error because `os` is being imported twice, once by the addition of this line and once by the import that `go_bindata` generates.

<img width="405" alt="osohno" src="https://cloud.githubusercontent.com/assets/406639/17374576/1e4597e8-5962-11e6-8ea1-e2bd21e67b96.png">

I don't believe the `os` addition is necessary for any set of underlying options sent to `go_bindata`. It looks like all of the possible import headers it could write out all include `os`:

- https://github.com/jteeuwen/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/release.go#L107
- https://github.com/jteeuwen/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/release.go#L144
- https://github.com/jteeuwen/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/release.go#L178
- https://github.com/jteeuwen/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/release.go#L205

**Comment by hheld** [comment]
That is correct, it turns out I had two versions of `go-bindata` on my machine, and the one that occurred in my `PATH` first didn't include `os`. But the latest version definitely does that already, such that an additional include isn't necessary.

Sorry for the confusion!

**Comment by imakewebthings** [comment]
@hheld No worries, thanks for the quick turnaround @elazarl 🙌

**Comment by themalkolm** [comment]
This fix actually breaks generated files and this import is required actually.

```
$ go build
...
./bindata_assetfs.go:289: undefined: os in os.FileInfo
./bindata_assetfs.go:290: undefined: os in os.Stat
```

Reverting it solves this problem.
