### ISSUE TITLE
Impossible to use theres no Assetfs function exported from the produced go code 

### ISSUE THREAD

**Issue by NikosEfthias** [elazarl/go-bindata-assetfs#44]
theres no function called `AssetFs` in the produced code

**Comment by danmondy** [comment]
I am confused by this also. The readme the says that the generated file provides an assetFS function... how is that possible when the function is private and my application is not aware of that binary? Can you please show all of the code?

**Comment by danmondy** [comment]
I believe it's lowercase assetFS()

**Comment by NikosEfthias** [comment]
I figured out that it should be the used within the same package and when doing `go run` you need to list both files, like `go run assets.go main.go`
