### ISSUE TITLE
some access error when use in windows 

### ISSUE THREAD

**Issue by luzhzhsoft** [elazarl/go-bindata-assetfs#50]
when I want  use go-bindata in windows system,some error happens.`D:\go\src\git.bwae.org\portal\cluster-admin>go-bindata-assetfs web\ui\...
bindata: open web\ui\...: Access is denied.
Error: go-bindata:  exit status 1
`

linux is ok.

**Comment by xiegeo** [comment]
Try running it from go generate.

**Comment by luzhzhsoft** [comment]
worth to try
