### ISSUE TITLE
Tag/Release v1.0.1

### ISSUE THREAD

**Issue by dvaldivia** [elazarl/go-bindata-assetfs#52]
On May 9th there was a PR that adds a fallback for Single page Applications. Right now the code is only in master, can you make a tag/release v1.0.1 so `go.mod` can reference directly to it and not master?

thanks!

**Comment by mfindlater** [comment]
Sure!

https://github.com/elazarl/go-bindata-assetfs/releases/tag/v1.0.1

**Comment by dvaldivia** [comment]
thanks!
